import type { Metadata } from 'next'
import Navbar from './components/navbar/Navbar'
import RegisterModal from './components/modals/RegisterModal'
import LoginModal from './components/modals/LoginModal'
import { Comfortaa } from 'next/font/google'
import ToasterProvider from './provider/ToasterProvider'
import getCurrentUser from './action/getCurrentUser'
import ClientOnly from './components/ClientOnly'
import RentModal from './components/modals/RentModal'
import SearchModal from './components/modals/SearchModal'
import './globals.css'
import Footer from './components/Footer'


export const metadata: Metadata = {
  title: 'Post Hotel',
  description: 'Generated by create next app',
}


const confotaa = Comfortaa({
  subsets: ['latin',],
  weight: ["400"],
})


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`${confotaa.className} min-h-screen `}>

        <div className="dark:bg-primary-dark px-6 min-h-screen">
          <ClientOnly >

            <Navbar currentUser={currentUser} />
            <RegisterModal />
            <SearchModal />
            <LoginModal />
            <RentModal />

            <ToasterProvider />
          </ClientOnly>

          <div className=" pb-20 pt-16">
            {children}
          </div>

        </div>
        <ClientOnly>
          <Footer />
        </ClientOnly>
      </body>
    </html>
  )
}
